# Generated by Django 4.2.5 on 2024-07-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_alter_formtransition_receivers_role_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(choices=[('Finance', 'Finance'), ('Logistic', 'Logistic'), ('Supply & Marketing', 'Supply & Marketing'), ('Technical', 'Technical'), ('Sourcing', 'Sourcing'), ('QMS', 'QMS'), ('CEO', 'CEO'), ('IT', 'IT')], max_length=45),
        ),
        migrations.AlterField(
            model_name='formtransition',
            name='receivers_role',
            field=models.CharField(choices=[('Department Moderator (Generic)', 'Department Moderator (Generic)'), ('CEO', 'CEO'), ('Chief Officer', 'Chief Officer'), ('CEO Deligate', 'CEO Deligate'), ('CFO', 'CFO'), ('Accountant', 'Accountant'), ('Business Development Manager', 'Business Development Manager'), ('Business Development Expert', 'Business Development Expert'), ('Marketing Moderator', 'Marketing Moderator'), ('Marketing Expert', 'Marketing Expert'), ('IT Expert', 'IT Expert'), ('Technical Moderator', 'Technical Moderator'), ('Logistic Expert', 'Logistic Expert'), ('Factory', 'Factory'), ('QC Expert', 'QC Expert'), ('Solar Development', 'Solar Development')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Department Moderator (Generic)', 'Department Moderator (Generic)'), ('CEO', 'CEO'), ('Chief Officer', 'Chief Officer'), ('CEO Deligate', 'CEO Deligate'), ('CFO', 'CFO'), ('Accountant', 'Accountant'), ('Business Development Manager', 'Business Development Manager'), ('Business Development Expert', 'Business Development Expert'), ('Marketing Moderator', 'Marketing Moderator'), ('Marketing Expert', 'Marketing Expert'), ('IT Expert', 'IT Expert'), ('Technical Moderator', 'Technical Moderator'), ('Logistic Expert', 'Logistic Expert'), ('Factory', 'Factory'), ('QC Expert', 'QC Expert'), ('Solar Development', 'Solar Development')], max_length=45),
        ),
    ]
